FROM alpine:3

LABEL author="Rizqi Pratama"
LABEL company="Verdko" website="https://rizqipratama.my.id" 

RUN mkdir hello
RUN echo "Hello DUUUINIIAAAAA" > "hello/world.txt"

CMD ["cat", "hello/world.txt"]